### ISSUE TITLE
Country Filter

### ISSUE THREAD

**Issue by sugarbeatsthat** [PromInc/organic-search-analytics#11]
Hi Brian,

Awesome job with this program and installation guide! I'm a complete novice at all this, but I just finished setting it up on my server, and it was all very easy.

I just wondered, is it complicated to set up a country filter for the reports? Can I do it by just adding a few lines to one of the PHP files? Have been having a look through the files, but nothing's jumping out at me. Would really appreciate a few pointers on how to do this.

Andy

**Comment by PromInc** [comment]
Hi Andy,

Thanks for the kudos - good to hear that a novice was able to figure it out.  My goal has been to make this something that is usable by all.  Sadly there are a few semi-technical items to put in place, but there's only so much I can do.  ;)

Admittedly, country is something that is a bit of an oversight on my part.  The tool is not designed to capture country data at this time.  Certainly something that should be in this tool.

If you are feeling ambitious, I think it could be possible with a bit of work...  I'll do my best to try and walk through it here, but I'll be honest I'm speaking this in theory and not out of code I've put in place (at this time at least....).  But this is a feature that I will make into the codebase at some point.

I should say though, the steps below will get the country data captured to the database.  Getting it to integrate to the reporting at this time is another can of worms I don't want to touch just yet.  I'm in the middle of a bit of a revamp on the reporting and what exists currently is too rudimentary.  I'm not saying it couldn't be integrated to what is there currently, and I think if you poke around in the reporting code enough you should be able to make something work.

## Database update

The database doesn't have a column to hold country data.  So that'd be the first step.  Use PhpMyAdmin or whatever database access you have to add a **country** column to the **search_analytics** table.  I'd suggest setting it to varchar(10).

## API Request Update

Next we need to modify the API request to capture the country field.  There are two ways to approach this depending on how you run the tool.

### GUI Method

IF you use the website interface only and do not utilize a CRON job or other programatic method to request data, then you'll need to make a small code tweak.  The big downside here is that as new versions get released this will get over-written and you'll need to re-apply this modification.

Change [Line 23 of inc/code/dataCapture.php](https://github.com/PromInc/organic-search-analytics/blob/master/organic-search-analytics/inc/code/dataCapture.php#L23) from:

```
'dimensions' => array('query','device'),
```

to:

```
'dimensions' => array('query','device','country'),
```

### Programatic Method

If you are using a CRON job or other programatic method to trigger the API request to Google, then you could simply do an override in your request.  There are several [data capture parameters](https://github.com/PromInc/organic-search-analytics/wiki/Data-Capture-Parameters) that allow you to make the same change that was made above but via a request as opposed to in the code.

Your request would look something like this:

```
... inc/code/dataCapture.php?dimensions=query,device,country ...
```

## Data Import Update

Lastly we need to write the country data to the database.  For this, go to [line 64 of inc/code/wmpimport.php](https://github.com/PromInc/organic-search-analytics/blob/master/organic-search-analytics/inc/code/wmtimport.php#L64) and change it from:

```
$import = "INSERT into ".MySQL::DB_TABLE_SEARCH_ANALYTICS."(domain, date, search_engine, search_type, device_type, query, impressions, clicks, ctr, avg_position) values('$domain', '$date', 'google', '$searchType', '$deviceType', '{$recordData['keys'][0]}','{$recordData['impressions']}','{$recordData['clicks']}','{$recordData['ctr']}','{$recordData['position']}')";
```

to:

```
$import = "INSERT into ".MySQL::DB_TABLE_SEARCH_ANALYTICS."(domain, date, search_engine, search_type, device_type, query, country, impressions, clicks, ctr, avg_position) values('$domain', '$date', 'google', '$searchType', '$deviceType', '{$recordData['keys'][0]}', '{$recordData['keys'][2]}','{$recordData['impressions']}','{$recordData['clicks']}','{$recordData['ctr']}','{$recordData['position']}')";
```

## Test Your Code

That should be it - your next data capture should pull in country data.

Let me know how this goes for you.  Your comments will help to ensure this gets integrated correctly into a future release.

**Comment by PromInc** [comment]
As of version 2.4.0 this issue has been added and thus resolved.

### Installation

Notice - you'll need to run an update script from the home page for this version to run smoothly as it needs to update the database.  Go to the homepage of your installation, choose **Upgrade Scripts** and then choose **Run Update for Version 2.x.x to 2.4.0**.  This does a database update to add the country column.

After this is all done, you could also choose to run the delete option (from home page) to delete data without country information and then re-capture data with the country.  This will give you the maximum amount of data available with the country.

### Reports

The initial report settings page is a bit "odd" when selecting a country as it will display ALL countries available from all domains, queries, date ranges, etc.  For that reason, it'd be possible to generate a report that pulls back no results.  However, once viewing a report, we have some information to base the country validation off of and thus the list is filtered down at that point.  So it may be best practice to generate a report with no country selected and then add the country in a second step.  Though if you are looking at the primary country that drives traffic to your site this may be a moot point.
