### ISSUE TITLE
Extract PAGES from GSC.

### ISSUE THREAD

**Issue by ctseo** [PromInc/organic-search-analytics#13]
It would be nice if we can extract PAGES from GSC and we could search query by pages to see positions and clicks.

**Comment by PromInc** [comment]
The Google API only allows us to pull 5000 rows per request.  This means that for websites with a large amount of traffic, it can be difficult to capture all of the data.

That said, in looking at how to best structure this request I'm struggling a bit on how to best proceed.  Let me explain.

Let's say your site gets traffic for the keyword **widgets** and that had 2,000 impressions for a given day for web search.  (the tool is doing three requests to the API for the three types of search types already - web (all), video, and image, so if it were 2,000 impressions for each it would total to 6,000).
1. 2,000 impressions for "widget"

So that's simple enough - we returned 1 row on that request for **widgets**.  However, as we add additional dimensions to the request we start to multiple the number of rows requested.  FYI - There are 4 dimensions that could be requested: **query**, **page**, **device**, and **country**.

If I say **query** and **country** for example (which the tool is doing currently), our keyword **widgets** could turn out to be something like:
1. 1,000 impressions for "widget" from US
2. 200 impressions for "widget" from GE
3. 10 impressions for "widget" from YEM
4. 1 impressions for "widget" from BEL

By adding one layer of granularity to the request, we now have created 4 rows in this example request.

And having device added to this as well (which the tool already does) will exasperate the issue even further.
1. 600 impressions for "widget" from US on DESKTOP
2. 300 impressions for "widget" from US on TABLET
3. 100 impressions for "widget" from US on MOBILE
4. 188 impressions for "widget" from GE on DESKTOP
5. 10 impressions for "widget" from GE on TABLET
6. 2 impressions for "widget" from GE on MOBILE
7. 5 impressions for "widget" from YEM on DESKTOP
8. 3 impressions for "widget" from YEM on TABLET
9. 2 impressions for "widget" from YEM on MOBILE
10. 1 impressions for "widget" from BEL on MOBILE

See how quickly this example is now at 10 rows?

So, adding one level deeper - pages - will make this pattern continue to grow.  I don't think I need to add an example, you get the point.

At this time I can think of two possible solutions to best approach this request.

### 1. User Option

Provide user options to select how granular the user wishes to make their data.
- Provide checkboxes in the settings page to allow them to determine which dimensions to capture - query, page, device, and/or country.  As highlighted here, the more granular the user gets the "less data" they will get in essence, but it'll be more accurate to the type of usage.

### 2. Re-Engineer Data Capture Process

Capture a list of all of the queries for that site via the API with NO dimensions set.  Then re-query the API for each query to capture all 4 dimensions for each query.
- This is a way to get essentially around the 5,000 row limit set by Google - or as close to it as possible.
- Potential downsides here however are:
  - Capturing data for a given day will take significantly longer
  - Potential to hit Google API request limitation (1,000,000 API calls per day.  That's roughly 66 days worth of data in one day.  So a new user couldn't capture all data for one site in one day.)
  - This will drastically increase the database filesize over time and potentially make reporting generation slower due to the mass amount of data
  - Much more effort on my part to implement this solution

I think ultimately the second option (Re-Engineer Data Capture Process) is the way to go here.  I was going to try and quick sneak this task in this week until I did some test API pulls and came across this.  So in typing this out here it helped me to understand how to best approach the task in an effort to capture the optimal amount of data, but it's turning into a larger task than I had first thought it might be.

Any feedback on the matter is greatly appreciated.

**Comment by PromInc** [comment]
A proposed solution to this issue suggested by **Alexander** at:
[http://promincproductions.com/blog/organic-search-analytics-capture-your-seo-data-from-search-engines/#comment-93](http://promincproductions.com/blog/organic-search-analytics-capture-your-seo-data-from-search-engines/#comment-93)


Edit file:

> /public_html/osam/inc/code/dataCapture.php

```
private $defaultGoogleSearchAnalyticsSettings = array(
‘mode’ => ‘import’, /* What to do with the data. Valid options: import, return */
‘dimensions’ => array(‘query’,’device’,’country’,’page’),
‘row_limit’ => 5000 /* Number of rows to capture from Google. Valid options: 1-5000 */
);
```

Then edit file
> /public_html/osam/inc/code/wmtimport.php

```
public function importGoogleSearchAnalytics($domain, $date, $searchType, $searchAnalytics) {
$countImport = 0;
foreach( $searchAnalytics->rows as $recordKey => $recordData ) {
/* Prep data */
$domain = addslashes( $domain );
$searchType = addslashes( $searchType );
$deviceType = addslashes( strtolower( $recordData[‘keys’][1] ) );
$country = addslashes( strtolower( $recordData[‘keys’][2] ) );
$query = addslashes( $recordData[‘keys’][0] );
$page = addslashes( $recordData[‘keys’][3]);

$import = “INSERT into “.MySQL::DB_TABLE_SEARCH_ANALYTICS.”(page,domain, date, search_engine, search_type, device_type, country, query, impressions, clicks, ctr, avg_position) values(‘$page’,’$domain’, ‘$date’, ‘google’, ‘$searchType’, ‘$deviceType’, ‘$country’, ‘{$query}’,'{$recordData[‘impressions’]}’,'{$recordData[‘clicks’]}’,'{$recordData[‘ctr’]}’,'{$recordData[‘position’]}’)”;

if( $GLOBALS[‘db’]->query($import) ) {
$countImport++;
}
}
return $countImport;
}
```

Oh, of course , you should add column “page” in search analytics table.
