### ISSUE TITLE
Keep START-END date 

### ISSUE THREAD

**Issue by ctseo** [PromInc/organic-search-analytics#24]
Hello,

On REPORTS, when you change something on settings or you change query, the page will load again and doesnt keep the START-END date. It woul be useful to keep this dates.

Another small issues, i cant select Country.
Would you have time to add PAGES in settings? It would be useful to filter by page and see all queries who linked to specific pages.

**Comment by PromInc** [comment]
### Dates

I'm not able to recreate the issue - can you please provide specific steps you have taken to create the problem?

### Country

The country will only be populated for Google starting with data captured using version 2.4.0 and later.  All data prior to that is **NULL** and thus the only _country_ that will show up for that data set is **ALL** as the list of countries is populated based on the _country_ data for your sites.

That said, my assumption is that you can't select it because none of your data has the country field populated.

I'd advise using the **Delete Data** tool found on the home page, then re-capture the data from Google using the **Data Capture** tool.  This will give you country data for the past 90 days and backfill as much of your database as possible.

### Pages

Page level data, as requested in Issue #13 is probably the next on my list.  But to be honest, not sure how quickly I'll get to that yet - I have a lot going on this and next week but would like to get to that soon.

**Comment by PromInc** [comment]
Due to lack of comments I'm assuming this issue has been resolved and thus am closing.
