### ISSUE TITLE
BAD encoding Russian Symbols

### ISSUE THREAD

**Issue by stereomoto** [PromInc/organic-search-analytics#32]
Hello

I've problem with saving Russian words.
Queries in russian saves in bad encoding.

![image](https://cloud.githubusercontent.com/assets/26055856/23352689/b6b0e1de-fcd9-11e6-9b2a-38feff6879a6.png)

Example of dataset in Russian

запрос 1
запрос 2
запрос 3
запрос 4
запрос 5
запрос 6

i mean that the problem is in encoding in database

![image](https://cloud.githubusercontent.com/assets/26055856/23352786/3b5d111e-fcda-11e6-8ff4-d98d4cf2c03b.png)

**Comment by stereomoto** [comment]
You can fix it easily by adding the code into /inc/code/wmtimport.php
```
`public function importGoogleSearchAnalytics($domain, $date, $searchType, $searchAnalytics) {

$countImport = 0;

**$GLOBALS['db']->query("SET CHARACTER SET UTF8");

$GLOBALS['db']->query("SET NAMES UTF8");**

foreach( $searchAnalytics->rows as $recordKey => $recordData ) {	`
```

**Comment by PromInc** [comment]
@stereomoto I appreciate you looking into this issue.  Glad to hear you were able to get to the source of the issue!

I appreciate your proposed solution.  I took it one step further and rather than fix the issue in PHP I say lets correct the database structure and correct the issue at the root of it.

I have added a branch with the changes - [Issue#32-Encoding](https://github.com/PromInc/organic-search-analytics/tree/Issue%2332-Encoding).  To be honest I haven't had a chance to test this yet but intend to in the next day or two.  You are more than welcome to test it as well - I'd suggest creating a new setup all together so as to not risk your current data set.

That branch will set the database correctly upon install.  Additionally, for those that are using an older version it provides an upgrade script that will correct the database configuration.

Additionally I noticed inconsistencies in the database engine used.  I have set all to Innodb.
