### ISSUE TITLE
Google_Auth_Exception Error

### ISSUE THREAD

**Issue by yxlofohn** [PromInc/organic-search-analytics#33]
Hi,

I would love to use your tool but got some problems in the setup process. It seems that your installation instructions are not up to date since the Google Developer Console interface might changed a bit. There is no email adress shown according to step 6. XVIII.

While clicking around I found an area called "manage Service Accounts" in Google Developer Console. But there are two different entries with email adresses.

One with @appspot.gserviceaccount.com and one with @developer.gserviceaccount.com. I tried both in the config.php and added both with full access to Google Search Console. Anyway I still get the following error:

"Domain:
Fatal error: Uncaught exception 'Google_Auth_Exception' with message 'Error refreshing the OAuth2 token, message: '{ "error" : "invalid_grant", "error_description" : "Invalid JWT: Token must be a short-lived token and in a reasonable timeframe" }'' in /volume1/web/organic-search/apis/Google/Auth/OAuth2.php:363 Stack trace: #0 /volume1/web/organic-search/apis/Google/Auth/OAuth2.php(314): Google_Auth_OAuth2->refreshTokenRequest(Array) #1 /volume1/web/organic-search/inc/code/gapiOauth.php(45): Google_Auth_OAuth2->refreshTokenWithAssertion() #2 /volume1/web/organic-search/inc/code/dataCapture.php(43): GAPIoAuth->LogIn() #3 /volume1/web/organic-search/inc/html/reportSettings.php(9): DataCapture->getSitesGoogleSearchConsole() #4 /volume1/web/organic-search/report.php(54): include_once('/volume1/web/or...') #5 {main} thrown in /volume1/web/organic-search/apis/Google/Auth/OAuth2.php on line 363"

I checked my config file as mentioned in issue #9. The p12 file has been added correctly with *.p12.
Do you have any idea of what is going wrong?

**Comment by PromInc** [comment]
Thank you for raising this issue.  I was aware that the dev console changed, started a revision to this instruction some time ago and life happened and sadly it fell off of my radar.

I have updated the instructions and tested - all works well with the updates.

The email address you need is a `@developer.gserviceaccount.com` address.  You find it by clicking on the **Manage service accounts** link.  See [step 6.xv](https://github.com/PromInc/organic-search-analytics/wiki/Installation) for full details.  But it sounds like you found that.

The same email address will be used in Search Console as well as in the Organic Search Analytics tool.

I'm not 100% sure what the root of your issue is.  My guess is that you maybe didn't have the Search Console API access enabled for you project.

I'd suggest going through the updated instructions, possibly even deleting any work you did prior and starting fresh to ensure a clean and accurate installation.

Let me know if this helps at all.

**Comment by yxlofohn** [comment]
Thx a lot! The tool is running now.

Are you sure that position and click data is aggregated correctly? I observed big differences to GSC.

Example:
GSC: KeyXY, 2386 Impressions, 161 Clicks, Pos 1,4
Search Analytics: KeyXY, 2372 Impressions, 1628 Clicks, Pos. 13,01

I know that it is normal to have some inaccuracy within API and frontend data but this diffenrence seems to be a bit too much.

**Comment by qstarx** [comment]
hi yxlofohn,

Aggregation is not correct. See patch https://github.com/PromInc/organic-search-analytics/pull/31
for getting proper results.

**Comment by PromInc** [comment]
Closing as the primary issue on this is resolved and the other issue is being tracked under #31.
