### ISSUE TITLE
Consider the aggregation type

### ISSUE THREAD

**Issue by Sawascwoolf** [PromInc/organic-search-analytics#4]
Hi,

I've found out a problem with the settings your tool uses to fetch data from google.
Possible Values for aggregationType:
- 'auto' [Default]
- 'byPage'
- 'byProperty'

I don't know how auto works at the moment, but you should consider the differences between byPage and byProperty.
The difference is described here: https://support.google.com/webmasters/answer/6155685#urlorsite

I'm starting a bit of testing the calculations which are performed when the 'auto' - parameter is used in comparison to the two others.

**Comment by PromInc** [comment]
Humm... this is a good point that I should probably be setting this value.

What is interesting, is the link you provided doesn't reference the AUTO setting.  The one place I've seen it referenced is the [Google API Explorer](https://developers.google.com/apis-explorer/#p/webmasters/v3/webmasters.searchanalytics.query).

There they state:

> [Optional; Default is "auto"] How data is aggregated. If aggregated by property, all data for the same property is aggregated; if aggregated by page, all data is aggregated by canonical URI. If you filter or group by page, choose AUTO; otherwise you can aggregate either by property or by page, depending on how you want your data calculated; see  the help documentation to learn how data is calculated differently by site versus by page.
> 
> Note: If you group or filter by page, you cannot aggregate by property.
> 
> If you specify any value other than AUTO, the aggregation type in the result will match the requested type, or if you request an invalid type, you will get an error. The API will never change your aggregation type if the requested type is invalid.

Based on this line, `If you filter or group by page, choose AUTO; otherwise you can aggregate either by property or by page, depending on how you want your data calculated` it sounds like `AUTO` only applies to grouping by page, which is not how I'm pulling the data.

That said, I did a quick test.  Here are the settings I'm using in the API Explorer, which mimic what the tool is doing.  Note that the `dimensions` and `rowLImit` are hard coded to these values in the tool at this time.  Also, the tests were done with one of my actual properties - the domain has been changed to example.com for illustration purposes.
![2015-09-11-google-api-explorer-search-analytics](https://cloud.githubusercontent.com/assets/7319505/9814407/78946028-5853-11e5-8022-fb13c1820d7c.png)

I then tried setting the `aggregationType` to `property` (as well as capitalization variations there of) which results in an error.

**Request**

```
POST https://www.googleapis.com/webmasters/v3/sites/http%3A%2F%2Fexample.com%2F/searchAnalytics/query

{
 "endDate": "2015-09-01",
 "startDate": "2015-08-31",
 "dimensions": [
  "query",
  "device"
 ],
 "searchType": "web",
 "rowLimit": 5000,
 "aggregationType": "property"
}
```

**Response**

```
400 OK

- Show headers -

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid value for: property is not a valid value"
   }
  ],
  "code": 400,
  "message": "Invalid value for: property is not a valid value"
 }
}
```

There is one more property that I am not setting at this time - `dimensionFilterGroups`.  The more I re-read the documentation, I think the `aggregationType` only applies when the 'dimensionFilterGroups' property is added - which allows you to either filter, group, or filter and group.  At this time I am not utilizing this property as I want to capture all data and allow querying of the data via MySQL within the reporting tool.

After having looked through this now, I do recall looking at all of these options when I designed this and the way that it is structured was intentional for the reason I just stated - I need to capture all of the data, and the `aggregationType` does not apply to how I'm capturing the data.  I am however interested in what your testing is finding.  Please let me know what you find.

**Comment by Sawascwoolf** [comment]
I've done some testing, but I couldn't find out how the values are calculated. the 'auto' and 'byProperty' seem to return the same result.
When checking data with 'byPage' and adding 'page' to _dimensions_ the results doesn't seem to make much sense. 

I've got a website which will show up with sitelinks for a specific search request and I think this makes it impossible to figure out how google calculates the results.

The results returned with setting "auto" are the ones which fits my needs.

**Comment by PromInc** [comment]
Thanks for doing the testing and sharing your results.  I'll continue to test how these various settings work as time permits as well in hopes of finding new and interesting ways to potentially capture and present data.  For now I'll consider this issue closed.

Sitelinks are some of the logic of Google that to the best of my knowledge is a bit of a mystery.  I know you can request to have sitelinks removed for certain queries via Google Search Console, but the entire system is not very clean or efficient on Googles part, that's for sure.  Best of luck!
