### ISSUE TITLE
Settings Page is Blank also Clicking RUN on Data Capture does nothing.

### ISSUE THREAD

**Issue by Ninjataktikz** [PromInc/organic-search-analytics#9]
Hi thank you for this great tool. I have set this up using MAMP. Configured all the files / followed all instructions step by step. After all said and done once I go to this through my webbrowser it asks me to configure the settings. Where i input MySql info  / p12 name / email from google developer console. It all registers fine creates a config.php file and what not but after that when I go click on Settings at the top. I get a BLANK page nothing there at all and also clicking on RUN does nothing for me. What am I doing wrong. Please help.

Thanks

**Comment by PromInc** [comment]
I did just test doing a download and test on my machine with the repository code and I had success.

I'm quite certain the issue lies in your config file or your connection to Google Analytics.  I know I've seen this issue before and that it was what I considered at the time to be operator error on my part and didn't have the time to troubleshoot it / implement a solution to prevent this to happen.  Though it may be in a bunch of code I haven't released yet - incomplete and not enough time to get back to it at the moment...  But I digress.

For starters, I'd ensure that you are using the correct email address from the [Google Developer Console. ](https://console.developers.google.com/) Use the email address from the **Service Account** - it should end with _@developer.gserviceaccount.com_.

Make sure the config.php and .p12 files are in the correct location.  You need to create a directory at the root level of the folder for the _Organic Search Analytics_ codebase named **config** (all lower case).  That is the directory that config.php and the .p12 file needs to be located.

There could be a potential issue in file permissions with these files.  If the web server can't read the config.php or .p12 file I could see problems occurring.  Right click on the config.php and p12 files and choose **Get Info** and ensure **read** access is set for everyone.

If none of that shows any improvements, check that the config.php file is correctly formatted and the values are populated correctly.  Set your values inside the quotes.

```
<?php
    class Config
    {
        const DB_CONNECTION_DOMAIN = 'localhost';
        const DB_CONNECTION_USER = 'root';
        const DB_CONNECTION_PASSWORD = 'root';
        const DB_CONNECTION_DATABASE = '';

        const OAUTH_CREDENTIALS_EMAIL = '';
        const OAUTH_CREDENTIALS_PRIVATE_KEY_FILE_NAME = '';

        const CREDENTIALS_BING_API_KEY = '';
    }
?>
```

I hope some of those suggestions help to correct the issue.  Please comment back here with any other findings or solutions you have so as to help others and offer insight on how to better improve the codebase to prevent this issue for others.

I'm far from done with building out this codebase, but at this time it's been put aside a bit.  As I see it, I need to ensure I can download the data - which when it's working it does great.  From there I can improve on the usability as time goes on.

**Comment by Ninjataktikz** [comment]
Thank you for the quick response. I forgot to mention that I am doing all this on Mac OS X (Yosemite). I will try these steps at work tomorrow and update with what I get.

Thank You

**Comment by Ninjataktikz** [comment]
Hi PromInc,

So I tested this again on Mac OS X (Yosemite).

I have my Organic Search Analytics under

htdocs > organic-search-analytics-2.2.0 > organic-search-analytics > config > .p12 & config.php file (with full write and read permissions) 

Also side note for host I am using 127.0.0.1 instead of localhost. - double checked my mysql connection via mamp it is up and running and I am able to connect to it via Sequel Pro.

I have created a user (email from google developer console) under google search console with full permissions to the url that i like to search under.

I have added the same email (service account email) in config file as well.

I still get BLANK page nothing showing. Followed everything thoroughly.

Also noob question but do I have to install any additional php libraries or anything else that is not mentioned in the instructions to make this work?

Thanks

**Comment by PromInc** [comment]
Can you view the home page at least?
http://127.0.0.1/organic-search-analytics-2.2.0/organic-search-analytics/

Using 127.0.0.1 shouldn't be an issue in my mind.

Here are some tests I ran on my end to try and break it (though I'm on a PC at the moment using XAMPP, but should be very similar results).
- Incorrectly named .p12 file throws PHP errors on settings.php
- Invalid MySQL credentials or database name throw an error at the top of the page and only render the menu bar across the top.  Then a PHP error is thrown.
- Invalid OAuth credentials throws a PHP error
- Invalid PHP in config.php file threw a white page with a PHP error

The last step I did there I'm guessing is the same issue you are running into.  I get a PHP error on the page, but depending on the PHP settings withing MAMP it may not throw errors.

You didn't comment about trying to manually re-write that file, that might be worth trying.  Textedit should work if you don't have another text editor.

The more I think about it though, might be worth trying to re-download the entire thing and start over.  I'm wondering if there is a corrupt file somewhere?  The config directory is the only thing that is unique from the repository outside of the database.  So you really won't loose any information.

As for your question regarding extra libraries, no there shouldn't be any.  The one library that is required is the Google API library, but that is included in the repository, so you already have that.

One interesting thing to note is that I noticed the Google Developer Console has been slightly updated since I last looked at it a few weeks ago as well as since I wrote the article you followed.  Maybe some steps in there have changed - not sure...

Sorry to hear you are having so many issues.  I've now done a clean install on two different machines attached to two different Google Developer Console accounts (copying a config folder I know is working) and had no issues.  Once on OS X Maverics using MAMP (non-pro) and once using XAMPP on Windows 8.1.  I'm running out of ideas as to what you are hitting up against!!!

**Comment by Ninjataktikz** [comment]
So that website does work for me. I think you are right about the php errors. It might be turned off under my settings I only see a blank page but no errors. Let me enable that and see what I get. Will update this soon.

**Comment by Ninjataktikz** [comment]
After turning on PHP Errors when I now click on settings this is what it throws at me.

https://gyazo.com/b4f0f115519feecd03b242b8f3b95247

I have given full write and read permissions to the config folder and all items inclosed as well.

Have you seen this before ? do I need to go change anything in that auth file under inc > codes

p.s. I did re-write the config file manually to see if that changes anything.

**Comment by PromInc** [comment]
While I hate seeing errors, they certainly do help to understand what is happening!!!

In your config.php file, try adding the file extension to the .p12 file name.

```
const OAUTH_CREDENTIALS_PRIVATE_KEY_FILE_NAME = 'Full File Name Here.p12';
```

**Comment by Ninjataktikz** [comment]
You sir are god. I don't know how i missed that. That was it. It must have the .p12 Extention in order for it to work.

:)    FINALLY Thanks.

**Comment by PromInc** [comment]
Glad to hear it's working!

**Comment by ctseo** [comment]
Hello PromInc, 

Thank you for your tools. Seems to be a great tool, but i want to see query value, not total numbers of query.

I want to see for example "keyword" - clicks, impressions, ctr, positions.

Can this tool extrat the value of all keywords & info that exist in GSConsole ?

**Comment by PromInc** [comment]
Hello @ctseo,

I'm glad to hear that you like the tool.

The current release of code does have very basic (or maybe better to say "archaic") reporting tools.  The initial goal of this tool was to capture data as accurately as possible from the Search Engines and store it locally so as to have as much data available as possible.  I feel that step is complete (at least from the search analytics data - I'd like to pull more data at some point.)

Then the next then is to enhance the reporting tools so the data can be a bit more useful.  I have a majority of this done on a local dev server.  But it's not pretty or complete yet...  But it does work I guess...  I don't have access to the dev server at the moment, but if I get a chance tomorrow I could upload the branch for you to take a look at (though I'll have to figure out a DB update script as well).

I hate that it's been so long since my last update to this repo - work and life has gotten crazy and so this project just hasn't been a focus at the moment.

As for your question regarding what data is captured from GSC, at this time it is only Search Analytics data, but it captures as much data as possible from GSC.  I just wrote up a Wiki article about what data is captured.
[Data Captured from Google Search Console](https://github.com/PromInc/organic-search-analytics/wiki/Data-Captured-from-Google-Search-Console)

I hope this information helps you.

**Comment by ctseo** [comment]
I love your tool @PromInc  :+1:  !

I'm waiting for new updates and improvements... ! if you will sell this tools as pro, i will buy licences for this tool ! Thank you for your interest of making SEOs work more easy.

**Comment by PromInc** [comment]
Thanks @ctseo I appreciate your comments and feedback.

I've tossed the idea of a paid version around in my head but don't know if I'll go that route at this time.  To be honest, it just feels good to give back to the community and help others.  But good to know that others have strong interest in this tool.

If you really feel so inclined to offer a monetary contribution for the tool, there is a donate button at the top of the tool, but don't feel obligated to.  Again - this is a free tool by design.

**Comment by ctseo** [comment]
![organicdesign](https://cloud.githubusercontent.com/assets/13134199/11744886/9f87a7a6-a01c-11e5-8970-cd9d4ff1aa86.jpg)

I've added some design improvements.

**Comment by ctseo** [comment]
I wish if you have time to add some little updates to report. Need a search filter by query ( if we export all queries from db), by clicking on the top of panel, or having a top module with some options.

And a comparations of saved results will be good for us !

**Comment by PromInc** [comment]
I REALLY like the grid layout!

If you ever want to create a pull request with updates, say some of these updates, I'd be open to reviewing that and integrating some of them.  I know the design could use some polishing but I'd rather focus most of my time on features.

Improved reporting features are in development already.  Likewise saved reports so you can quickly get back to a common report.  However an export is not something I have started into.  I've done it in the past with other tools so I know how to get there just needs to be done.

Comparisons is something that I've thought of but is not on a roadmap or plan at this time.  I do see the value in the feature though.

**Comment by PromInc** [comment]
Release 2.3.0 added reports organized by Query (or keyword) as requested above.
